### PR TITLE
Making frontend search fields overridable.

### PR DESCRIPTION
**Pull request by codewp**
This branch adds an improvements in Easy Property Listings front-end search fields that developers can override them by removing default actions for front-end search fields and adding their desired actions for displaying front-end search fields.

### CODE REVIEW

**Comment by mervb** [comment]
Awesome, am working on a few other fixes and will release this fix with the others. Thanks so much for contributing

**Comment by mervb** [comment]
This is some incredable work codewp

**Comment by mervb** [comment]
packaging up 2.4 currently and will push a branch to the EPL core when ready. Lots of changes and what you did looks magnificent but am not completely sure what it does/ how to use it

**Comment by codewp** [comment]
Excuse me Merv I should created two another branch based on this branch for epl_search functionality.

I created a gist for override front-end search fields of EPL [override-epl-search-fields](https://gist.github.com/codewp/d9000588bacc61f5d6fb).
As you can see in above example developers can replace default frontend search fields with their own search fields.

Also I created a gist for using epl_search function [epl-search](https://gist.github.com/codewp/a399f8c5a20980d8e30e).

I hope these examples will help you to understand how to use these features.

**Comment by mervb** [comment]
I've prepped 2.4 but have some errors with it. I've merged your changes with ours and there are a few issues. I'll push the merged 2.4 beta branch to the epl core.

**Comment by mervb** [comment]
2.4 Beta merged with your changes to this branch

https://github.com/easypropertylistings/Easy-Property-Listings/pull/157

Notes with issues shown.

**Comment by mervb** [comment]
We are working on the errors and will push to the branch when complete for testing. I'll let you know once that is done so you don't need to work on something we are already working on

**Pull request merged**
