### PR TITLE
Trying add "numbers of Rooms"

### PR DESCRIPTION
**Pull request by aleks-nl5**
Added - to the "numbers of Rooms" in admin panel (“Edit Listing (Property and Rentals) – Listing Features – House Features”) line “Rooms”.

Added - on the list “All Listing” (Property and Rentals) in the column “Listing Details” is shown as “Beds” and “Baths”.
Added - in search widget – checkbox “Rooms”.
Added - Brought to the page “Single listing” in section “Property Features”.

ToDo - could not overpower the conclusion of icons (such as the “pool” and “beds”).
ToDo - did not work to add to the search widget.

### CODE REVIEW

**Comment by mervb** [comment]
Awesome work, give me a couple of days to test this

On Thu, Jan 15, 2015 at 2:01 AM, Alex <notifications@github.com> wrote:

> Added - to the "numbers of Rooms" in admin panel (“Edit Listing (Property
> and Rentals) – Listing Features – House Features”) line “Rooms”.
>
> Added - on the list “All Listing” (Property and Rentals) in the column
> “Listing Details” is shown as “Beds” and “Baths”.
> Added - in search widget – checkbox “Rooms”.
> Added - Brought to the page “Single listing” in section “Property
> Features”.
>
> ToDo - could not overpower the conclusion of icons (such as the “pool” and
> “beds”).
> ToDo - did not work to add to the search widget.
> ------------------------------
> You can merge this Pull Request by running
>
>   git pull https://github.com/aleks-nl5/Easy-Property-Listings 1.3-public-beta-3
>
> Or view, comment on, or merge it at:
>
>   https://github.com/easypropertylistings/Easy-Property-Listings/pull/61
> Commit Summary
>
>    - Added - to the "numbers of Rooms" in admin panel (“Edit Listing
>    (Property and Rentals) – Listing Features – House Features”) line “Rooms”.
>
> File Changes
>
>    - *M* lib/compatibility/listing-meta-compat.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-0>
>    (19)
>    - *M* lib/includes/class-property-meta.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-1>
>    (10)
>    - *M* lib/includes/template-functions.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-2>
>    (1)
>    - *M* lib/meta-boxes/meta-boxes.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-3>
>    (6)
>    - *M* lib/post-types/post-type-property.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-4>
>    (6)
>    - *M* lib/post-types/post-type-rental.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-5>
>    (6)
>    - *M* lib/post-types/post-type-rural.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-6>
>    (6)
>    - *M* lib/shortcodes/shortcode-listing-search.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-7>
>    (33)
>    - *M* lib/templates/content/content-listing-search.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-8>
>    (7)
>    - *M* lib/widgets/widget-listing-search.php
>    <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61/files#diff-9>
>    (8)
>
> Patch Links:
>
>    -
>    https://github.com/easypropertylistings/Easy-Property-Listings/pull/61.patch
>    -
>    https://github.com/easypropertylistings/Easy-Property-Listings/pull/61.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/easypropertylistings/Easy-Property-Listings/pull/61>.
>



-- 
Merv Barrett

*Real Estate Connected*
*+61894680006*
merv@realestateconnected.com.au
http://www.realestateconnected.com.au

**Comment by aleks-nl5** [comment]
Great, Thanks!
P.S. One thing - if all be good, need update .pot file for translation (i am preparing translation for Ukrainian and Russian languages) but i don't know how to update.

**Comment by mervb** [comment]
Hi Aleks

Made significant changes to core, its version 2.0

Am updating translation pot file. New base is the master branch. HAve yet to review your rooms changes as we are no long using listing-meta.php with 2.0

**Comment by aleks-nl5** [comment]
Hi Merv - Thank you for not forgotten about my request!
Just checked the working capacity with the original file "/lib/compatibility/listing-meta-compat.php" - and it works.
Initially, I could not get it "appear" field in the widget to search by number of rooms, and besides, at first I did not quite understand the purpose of the folder "compatibility" - and therefore brought back the change.

**Comment by aleks-nl5** [comment]
"Am updating translation pot file. New base is the master branch."
Sorry but I don't see updated file, just new comment. Date of change - "14 days ago".
And when I open it to update in Poedit - he says "there is nothing to update"...
lang

**Comment by mervb** [comment]
Translation update was not done... will do today.

Had an issue with how we were working with git. It wasn't a good way but have now rectified that process. Still learning git too.

Secondly
The compatibility folders are for old code to ensure older extensions still work with the plugin and older templates but this code was... not the best.

We are now implementing everything through a global $property variable which is handy for new fields outside of the core code.

How it all works

single-listing.php executes the new simple hook  <?php do_action( 'epl_property_single' ); ?>

That action loads the default template file like before, however if you look inside the default template file you will see major changes in comparison to 1.2. IE a hell of a lot easier to understand, modify and use.

I'll be putting together more documentation for all this.

Activate the updated master and visit the Getting Started page and whats new as i have made documentation much better and easier to understand.

I should be back in the office where to build the pot files again in a few hours.

**Pull request closed without merging**
